# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/top_system_ila_0_1.xci
# IP: The module: 'top_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/bd_c657.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c657 || ORIG_REF_NAME==bd_c657} -quiet] -quiet

# IP: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/bd_c657_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c657_ila_lib_0 || ORIG_REF_NAME==bd_c657_ila_lib_0} -quiet] -quiet

# IP: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_1/bd_c657_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c657_g_inst_0 || ORIG_REF_NAME==bd_c657_g_inst_0} -quiet] -quiet

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/top_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c657_ila_lib_0 || ORIG_REF_NAME==bd_c657_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c657_ila_lib_0 || ORIG_REF_NAME==bd_c657_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/bd_c657_ila_lib_0_ooc.xdc

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/bd_c657_ooc.xdc

# IP: C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/top_system_ila_0_1.xci
# IP: The module: 'top_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/bd_c657.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c657 || ORIG_REF_NAME==bd_c657} -quiet] -quiet

# IP: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/bd_c657_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c657_ila_lib_0 || ORIG_REF_NAME==bd_c657_ila_lib_0} -quiet] -quiet

# IP: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_1/bd_c657_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c657_g_inst_0 || ORIG_REF_NAME==bd_c657_g_inst_0} -quiet] -quiet

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/top_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c657_ila_lib_0 || ORIG_REF_NAME==bd_c657_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c657_ila_lib_0 || ORIG_REF_NAME==bd_c657_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/bd_c657_ila_lib_0_ooc.xdc

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/bd_c657_ooc.xdc
