# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.cache/wt [current_project]
set_property parent.project_path C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/new/FFT_2D_Top.v
  C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/new/FFT_Top_16.v
  C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/new/FFT_Top_256.v
  C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/hdl/top_wrapper.v
}
add_files C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axis_data_fifo_0_0/top_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_rst_clk_wiz_100M_0/top_rst_clk_wiz_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_rst_clk_wiz_100M_0/top_rst_clk_wiz_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_rst_clk_wiz_100M_0/top_rst_clk_wiz_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/top_system_ila_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/bd_c657_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/bd_c657_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_xbar_0/top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axis_data_fifo_0_1/top_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_auto_us_0/top_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_auto_us_0/top_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_auto_us_0/top_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_auto_us_1/top_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_auto_us_1/top_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_auto_us_1/top_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_auto_pc_0/top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_auto_pc_1/top_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/top_ooc.xdc]

read_ip -quiet C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/xfft_0/xfft_0_ooc.xdc]

read_ip -quiet C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/dual_port_ram/dual_port_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/dual_port_ram/dual_port_ram_ooc.xdc]

read_ip -quiet C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]

read_ip -quiet C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/xfft_1/xfft_1.xci
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/xfft_1/xfft_1_ooc.xdc]

read_ip -quiet C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_wrapper -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
