# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axis_data_fifo_0_1/top_axis_data_fifo_0_1.xci
# IP: The module: 'top_axis_data_fifo_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axis_data_fifo_0_1/top_axis_data_fifo_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axis_data_fifo_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axis_data_fifo_0_1/top_axis_data_fifo_0_1.xci
# IP: The module: 'top_axis_data_fifo_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/Tensor/2D_FFT_0_final/dma_test.srcs/sources_1/bd/top/ip/top_axis_data_fifo_0_1/top_axis_data_fifo_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axis_data_fifo_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
